name: build
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - name: Install GCC 11
        run: sudo apt update && sudo apt install -y gcc-11
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build ranges binary
        run: make
      - name: Check that ranges is more than 20x faster than Python script
        run: make perf-comparison
