name: tests
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install gcc-11 and valgrind
        run: sudo apt update && sudo apt install -y gcc-11 valgrind
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build ranges binary
        run: make
      - name: Run tests
        run: make tests
