name: tests
on:
  push:
    branches: [ "feature-13-continuous-integration" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build ranges binary
        run: make
      - name: Run tests
        run: make tests
